### ISSUE TITLE
Missing tag: get psyched (imp crew) 

### ISSUE THREAD

**Issue by Sereri** [Awful/thread-tags#1]
Hope it's OK I post this here. I can bring it up in the project.log thread if you want, this just seemed more appropriate to me. 

http://forumimages.somethingawful.com/forums/posticons/ycs-psyched.gif#454

**Comment by nolanw** [comment]
@Sereri works for me, dunno if @diabolik900 and @Ridilla are subscribed to this repo or not (but now they're subscribed to this issue!)

**Comment by diabolik900** [comment]
I saw this issue 27 days ago and then forgot about it. Whoops. Does anyone know the context of this tag? Is there a larger version of the text somewhere?

**Comment by nolanw** [comment]
@diabolik900 I'd ask in the IYG thread, never takes long for someone to fill in the details

**Comment by JonET** [comment]
The context is the Wolfenstein3D loading screen.
http://vignette1.wikia.nocookie.net/wolfenstein/images/e/ee/Wolfpsyched2.png/revision/latest?cb=20150401111818

**Comment by baka-kaba** [comment]
What about one of these

![1](https://user-images.githubusercontent.com/6281947/30004261-e9a0bf14-90c3-11e7-98ae-8ab12cfe79bd.png)
![2](https://user-images.githubusercontent.com/6281947/30004262-e9a3a4f4-90c3-11e7-9c62-002a94d8c66e.png)
![3](https://user-images.githubusercontent.com/6281947/30004263-e9a6fd3e-90c3-11e7-81fd-f76d9e9379b0.png)
![4](https://user-images.githubusercontent.com/6281947/30004264-e9a8439c-90c3-11e7-9b1a-d6c2399fb75d.png)

as you can see I'm an accomplished designer and that is a readable font

**Comment by JonET** [comment]
![get_psyched](https://user-images.githubusercontent.com/1863450/30044174-63abb89c-91c1-11e7-9f0f-f7ddfd577990.png)

**Comment by nolanw** [comment]
lgtm! Fire it into the repo if you're happy with it @JonET! Or holler if I can help.

**Comment by JonET** [comment]
Okay, done.
